trigger:
  - main

pool:
    name: 'mypool'
    demands:
    - agent.os -equals Windows

variables:
  TF_VAR_client_id: $(ARM_CLIENT_ID)
  TF_VAR_client_secret: $(ARM_CLIENT_SECRET)
  TF_VAR_subscription_id: $(ARM_SUBSCRIPTION_ID)
  TF_VAR_tenant_id: $(ARM_TENANT_ID)

stages:
  - stage: TerraformPlan
    jobs:
      - job: Plan
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: 'latest'
          - script: |
              terraform init
              terraform plan -out=tfplan
            displayName: 'Terraform Init and Plan'

  - stage: TerraformApply
    jobs:
      - job: Apply
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: 'latest'
          - script: |
              terraform apply -auto-approve tfplan
            displayName: 'Terraform Apply'
