trigger:
  - main

pool:
    name: 'mypool'
    demands:
    - agent.os -equals Windows


variables:
  ARM_CLIENT_ID: $(ARM_CLIENT_ID)
  ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
  ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
  ARM_TENANT_ID: $(ARM_TENANT_ID)

stages:
  - stage: TerraformPlan
    jobs:
      - job: Plan
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: 'latest'
          - script: |
              echo "Logging into Azure..."
              az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
              terraform init
              terraform plan -out=tfplan
            displayName: 'Terraform Init and Plan'

  - stage: TerraformApply
    jobs:
      - job: Apply
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: 'latest'
          - script: |
              echo "Logging into Azure..."
              az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
              terraform apply -auto-approve tfplan
            displayName: 'Terraform Apply'
