trigger:
  - None

pool:
 name: 'mypool'

stages:
  - stage: Terraform
    displayName: Terraform Build stage
    jobs:
    - job: Build
      displayName:  Terraform Build Job
      steps:
      - task: TerraformInstaller@1
        inputs: 
          terraformVersion: 'latest'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'Myconnectionactive'
          backendAzureRmOverrideSubscriptionID: '12486a52-70e3-4ae6-9f94-e6bacd147419'
          backendAzureRmResourceGroupName: 'demonewtest_group'
          backendAzureRmStorageAccountName: 'demonewtestgroupa219'
          backendAzureRmContainerName: 'demonew'
          backendAzureRmKey: 'trf/terraform.tfstate'


      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          commandOptions: '-lock=false'''
          environmentServiceNameAzureRM: 'Myconnectionactive'
          environmentAzureRmOverrideSubscriptionID: '12486a52-70e3-4ae6-9f94-e6bacd147419'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'apply'
          commandOptions: '--auto-approve'
          environmentServiceNameAzureRM: 'Myconnectionactive'
          environmentAzureRmOverrideSubscriptionID: '12486a52-70e3-4ae6-9f94-e6bacd147419'
      

